# Generated by Django 4.2.25 on 2025-11-05 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cards_reviewed', models.IntegerField(default=0)),
                ('cards_correct', models.IntegerField(default=0)),
                ('cards_incorrect', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('recommended_items', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_recommendations',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('kanji', 'Kanji'), ('grammar', 'Grammar')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_reviews', models.IntegerField(default=0)),
                ('correct_reviews', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'srs_cards',
                'ordering': ['next_review'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
