# Generated by Django 4.2.25 on 2025-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='front',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='content_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('kanji', 'Kanji'), ('grammar', 'Grammar'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
