# Generated by Django 4.2.25 on 2025-11-05 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grammar_pattern', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('formation', models.TextField()),
                ('usage_notes', models.TextField(blank=True)),
                ('jlpt_level', models.CharField(blank=True, choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2, null=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_grammar', models.ManyToManyField(blank=True, to='grammar.grammarpoint')),
            ],
            options={
                'db_table': 'grammar_points',
            },
        ),
        migrations.CreateModel(
            name='UserGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='learning', max_length=20)),
                ('times_studied', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='grammar.grammarpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_grammar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_grammar',
                'unique_together': {('user', 'grammar')},
            },
        ),
    ]
