# Generated by Django 4.2.25 on 2026-01-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanaLeaderboardScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=5)),
                ('kana_type', models.CharField(choices=[('hiragana', 'Hiragana'), ('katakana', 'Katakana'), ('mixed', 'Mixed')], max_length=10)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('time_seconds', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('score', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('wrong_answers', models.IntegerField()),
                ('best_streak', models.IntegerField()),
                ('session_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kana_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kana_leaderboard_scores',
                'ordering': ['time_seconds', '-accuracy', '-created_at'],
                'indexes': [models.Index(fields=['kana_type', 'difficulty', 'time_seconds'], name='kana_leader_kana_ty_3740b4_idx'), models.Index(fields=['created_at'], name='kana_leader_created_400b93_idx')],
            },
        ),
    ]
