# Generated by Django 4.2.25 on 2026-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_kanaleaderboardscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanaleaderboardscore',
            name='difficulty',
            field=models.CharField(choices=[('monographs', 'Monographs'), ('diacritics', 'Diacritics'), ('digraphs', 'Digraphs')], max_length=15),
        ),
        migrations.AlterField(
            model_name='kanaleaderboardscore',
            name='kana_type',
            field=models.CharField(choices=[('hiragana', 'Hiragana'), ('katakana', 'Katakana')], max_length=10),
        ),
    ]
