# Generated by Django 4.2.25 on 2026-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0003_alter_kanaleaderboardscore_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kanaleaderboardscore',
            name='kana_leader_kana_ty_3740b4_idx',
        ),
        migrations.RemoveField(
            model_name='kanaleaderboardscore',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='kanaleaderboardscore',
            name='variant_key',
            field=models.CharField(default='monographs', max_length=50),
        ),
        migrations.AddIndex(
            model_name='kanaleaderboardscore',
            index=models.Index(fields=['kana_type', 'variant_key', 'time_seconds'], name='kana_leader_kana_ty_653493_idx'),
        ),
    ]
