# Generated by Django 4.2.25 on 2025-11-05 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1, unique=True)),
                ('meaning', models.TextField()),
                ('kun_reading', models.CharField(blank=True, max_length=200)),
                ('on_reading', models.CharField(blank=True, max_length=200)),
                ('jlpt_level', models.CharField(blank=True, choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2, null=True)),
                ('stroke_count', models.IntegerField(default=0)),
                ('radical', models.CharField(blank=True, max_length=10)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kanji',
                'ordering': ['frequency_rank'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('reading', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('jlpt_level', models.CharField(blank=True, choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2, null=True)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('example_sentences', models.JSONField(blank=True, default=list)),
                ('pitch_accent', models.CharField(blank=True, max_length=50)),
                ('audio_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_kanji', models.ManyToManyField(blank=True, related_name='vocabulary', to='vocabulary.kanji')),
            ],
            options={
                'db_table': 'vocabulary',
                'ordering': ['frequency_rank'],
            },
        ),
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='learning', max_length=20)),
                ('times_studied', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_vocabulary', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='vocabulary.vocabulary')),
            ],
            options={
                'db_table': 'user_vocabulary',
                'unique_together': {('user', 'vocabulary')},
            },
        ),
        migrations.CreateModel(
            name='UserKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='learning', max_length=20)),
                ('times_studied', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('can_recognize', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('last_studied', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='vocabulary.kanji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_kanji', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_kanji',
                'unique_together': {('user', 'kanji')},
            },
        ),
        migrations.CreateModel(
            name='KanjiMnemonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnemonics', to='vocabulary.kanji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_mnemonics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kanji_mnemonics',
                'unique_together': {('kanji', 'user')},
            },
        ),
    ]
