# Generated by Django 4.2.25 on 2025-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_kanji_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='svg',
            field=models.CharField(blank=True, help_text='Path to SVG file for this Kanji', max_length=256),
        ),
    ]
